apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-octodet
spec:
  containers:
  - image: nginx
    name: nginx-octodet
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
